# Generated by Django 5.2.12 on 2026-03-21 05:50

import schematics.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schematic',
            name='file_litematica',
            field=models.FileField(blank=True, null=True, upload_to='litematica_files/', validators=[schematics.validators.validate_schematic_size, schematics.validators.validate_schematic_extension], verbose_name='Файл схемы'),
        ),
        migrations.AlterField(
            model_name='schematic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schematics/', validators=[schematics.validators.validate_image_size, schematics.validators.validate_image_extension], verbose_name='Картинка схемы'),
        ),
    ]
